services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: ideanick      
      POSTGRES_USER: postgres        
      POSTGRES_PASSWORD: postgre 
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4:latest  
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  
      PGADMIN_DEFAULT_PASSWORD: admin          
    ports:
      - "5050:80" 
    depends_on:
      - db  
    networks:
      - postgres_network
        
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"  # SMTP port
      - "4001:8025"  # Web UI port
    networks:
      - postgres_network
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: "true"
      MP_SMTP_AUTH_ALLOW_INSECURE: "true"
    # Make sure the container is accessible by hostname
    hostname: mailpit

volumes:
  postgres_data:  # Volume for PostgreSQL data persistence

networks:
  postgres_network:  # Network for communication between services